/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package it.grid.storm.filesystem.swig;

public class not_found {

  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected not_found(long cPtr, boolean cMemoryOwn) {

    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(not_found obj) {

    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {

    delete();
  }

  public synchronized void delete() {

    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        posixapi_interfaceJNI.delete_not_found(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public not_found(String msg) {

    this(posixapi_interfaceJNI.new_not_found(msg), true);
  }

}
