<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.italiangrid</groupId>
  <artifactId>storm-native-interface</artifactId>
  <version>2.1.0</version>
  <packaging>jar</packaging>

  <name>storm-native-interface</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <slf4j.version>1.7.2</slf4j.version>

    <!-- maven plugins -->
    <plugin.compiler.version>3.13.0</plugin.compiler.version>
    <plugin.enforcer.version>3.5.0</plugin.enforcer.version>

	<!-- java -->
    <java.version>17</java.version>

  </properties>

  <build>
    <plugins>
      <!-- Enforce maven version -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>${plugin.enforcer.version}</version>
        <executions>
          <execution>
            <id>enforce-maven</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireMavenVersion>
                  <version>3.6.3</version>
                </requireMavenVersion>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!-- Enable maven compiler plugin -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${plugin.compiler.version}</version>
        <configuration>
          <source>17</source>
          <target>17</target>
      </configuration>
      </plugin>
    </plugins>
  </build>
  <dependencies>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>${slf4j.version}</version>
    </dependency>

  </dependencies>

  <profiles>
    <profile>
      <id>local-staging</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <distributionManagement>
        <repository>
          <id>cnaf-releases</id>
          <name>CNAF releases</name>
          <url>https://repo.cloud.cnaf.infn.it/repository/cnaf-releases/</url>
        </repository>

        <snapshotRepository>
          <id>cnaf-snapshots</id>
          <name>CNAF snapshots</name>
          <url>https://repo.cloud.cnaf.infn.it/repository/cnaf-snapshots/</url>
        </snapshotRepository>
      </distributionManagement>
    </profile>
  </profiles>
</project>
