STUBS_DIR=../main/java/it/grid/storm/filesystem/swig

POSIX_INTERFACE= \
	posixapi_interface.i \
	pass_vector_by_value_java.i

GPFS_INTERFACE= \
	gpfsapi_interface.i \
	pass_vector_by_value_java.i

JAVA_PACKAGE=it.grid.storm.filesystem.swig

JNI_HEADER_LOCATION=/Developer/SDKs/MacOSX10.6.sdk/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Headers
JNI_MD_HEADER_LOCATION=/Developer/SDKs/MacOSX10.6.sdk/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Headers

all: posix-stubs posix-lib 

clean: 
	rm -f *.cxx *.o ../main/java/it/grid/storm/filesystem/swig/*.java

posix-stubs:  $(POSIX_INTERFACE)
	swig -c++ -java -package $(JAVA_PACKAGE) -outdir $(STUBS_DIR) -Wall posixapi_interface.i 

posixapi_srcs := \
    posixfs.cpp \
    genericfs.cpp \
    fs_acl.cpp \
    posixfs_acl.cpp \
    fs_errors.cpp \
    util.cpp

posixapi_objs := $(posixapi_srcs:.cpp=.o)

posixapi_swig_output_cxx := \
    posixapi_interface_wrap.cxx


posix-lib: posixapi_interface_wrap.o


posixapi_interface_wrap.o: posixapi_interface_wrap.cxx
	g++ -I$(JNI_HEADER_LOCATION) -I$(JNI_MD_HEADER_LOCATION) 
	
